### ISSUE TITLE
Path broken for live streams

### ISSUE THREAD

**Issue by ascagnel** [AgomezGZ/HockeyPlex.bundle#1]
When I try to open a live stream, for both automatic and specific servers, I get errors when viewing a stream.

```
Nov 20, 2015 22:02:14 [0x7f2b287ff700] ERROR - [Transcoder] http://watch.hscontent.com//PREMIUM_HSTV_21HD_m.m3u8?token=[withheld]: Invalid data found when processing input
```

When I view the game page, it gives me a similar URL, but the top-most path has a server entry (here, I was automatically assigned to `eu7`):

```
http://watch.hscontent.com/eu7/PREMIUM_HSTV_21HD.m3u8?token=[withheld]
```

**Comment by ascagnel** [comment]
On further inspection, this looks like it's the fault of HockeyStreams.

**Comment by AgomezGZ** [comment]
It is a HockeyStreams error, It should assign automatically a server...
